# Generated by Django 5.1.1 on 2024-09-25 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_profile_subcategory_uploadpets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.category'),
        ),
        migrations.AlterField(
            model_name='uploadpets',
            name='subcategory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.subcategory'),
        ),
    ]
