# Generated by Django 5.1.1 on 2024-09-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_uploadpets_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpets',
            name='subcategory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subcategory'),
        ),
    ]
