# Generated by Django 5.1.1 on 2024-09-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_uploadpets_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadpets',
            old_name='sluge',
            new_name='slug',
        ),
    ]
