# Generated by Django 5.1.1 on 2024-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpets',
            name='uploade_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
