# Generated by Django 5.1.1 on 2024-11-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_uploadpets_uploade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpets',
            name='published',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
